POST http://{{host}}/api/v1/users/create
Content-Type: application/json

{
  "name": "Luis",
  "email": "luis@api.com"
}

###

PUT http://{{host}}/api/v1/users/activate
Content-Type: application/json

{
  "email": "luis@api.com",
  "token": "7b4ca0f335e8b305865924971eb862d779d5654c",
  "password": "password"
}

###

POST http://{{host}}/api/v1/users/login_check
Content-Type: application/json

{
  "username": "luis@api.com",
  "password": "password"
}

###

PUT http://{{host}}/api/v1/users/e7d732a6-286e-4fc3-942f-4d0c7e92ff3d/change_password
Content-Type: application/json
Authorization: {{token}}

{
  "oldPass": "password",
  "newPass": "new-password"
}

###

GET http://{{host}}/api/v1/users/a154c8a5-bb2e-4f03-9720-0ac50ec08f12
Accept: application/json
Authorization: {{token}}

###

###

GET http://{{host}}/api/v1/users
Accept: application/json
Authorization: {{token}}

###

###

PUT http://{{host}}/api/v1/users/1d011c12-2dcf-4f7d-9572-2410c26f0e1b
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Jose Luis"
}

###

###
POST http://{{host}}/api/v1/users/a154c8a5-bb2e-4f03-9720-0ac50ec08f12/upload_avatar
Accept: */*
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{token}}

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"

// The 'avatar.jpg' file will be uploaded
< ./fixtures/avatar.jpg

###
