POST http://{{host}}/api/v1/account/create
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Conta Gas",
  "condoId": "fc6c100c-b24a-4f54-822a-1c1d8e7a7829"
}

###

PUT http://{{host}}/api/v1/account/f32258a6-c29f-4f91-b62c-1906c11418e8
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Conta exclusiva para Gas"
}

###