POST http://{{host}}/api/v1/users/create
Content-Type: application/json

{
  "name": "Santi",
  "email": "santi2@api.com"
}

###

PUT http://{{host}}/api/v1/users/activate
Content-Type: application/json

{
  "email": "santi2@api.com",
  "token": "fdc624cf2d241928b0194f40b95b18e28310411b",
  "password": "password"
}

###

POST http://{{host}}/api/v1/users/login_check
Content-Type: application/json

{
  "username": "santi2@api.com",
  "password": "password"
}

###

PUT http://{{host}}/api/v1/users/c92f7694-8511-4f18-85ee-9cff6cebfbc0/change_password
Content-Type: application/json

{
  "oldPass": "password",
  "newPass": "nwe-password"
}

###
GET http://{{host}}/api/v1/users/c92f7694-8511-4f18-85ee-9cff6cebfbc0
Accept: application/json

###