#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /api/v1/health-check
    controller: App\Controller\HealthCheckController
    methods: [GET]

# User
#api_get_user:
#    path: /api/v1/users
#    controller: App\Controller\User\GetUserAction
#    methods: [ GET ]

api.user.get:
    path: /api/v1/users/{id}
    controller: App\Controller\User\GetUserByIdAction
    methods: [ GET ]

api_create_user:
    path: /api/v1/users/create
    controller: App\Controller\User\CreateUserAction
    methods: [POST]

api_activate_user:
    path: /api/v1/users/activate
    controller: App\Controller\User\ActivateUserAction
    methods: [PUT]

# Condo
api_create_condo:
    path: /api/v1/condos/create
    controller: App\Controller\Condo\CreateCondoAction
    methods: [POST]
