#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /api/v1/health-check
    controller: App\Controller\HealthCheckController
    methods: [GET]

# User
api_create_user:
    path: /api/v1/users/create
    controller: App\Controller\User\CreateUserAction
    methods: [POST]

api_activate_user:
    path: /api/v1/users/activate
    controller: App\Controller\User\ActivateUserAction
    methods: [PUT]
