#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
    path: /api/v1/health-check
    controller: App\Controller\HealthCheckController
    methods: [GET]

# User
api_register_user:
    path: /api/v1/users/register
    controller: App\Controller\User\RegisterAction
    methods: [POST]

